### ISSUE TITLE
Update Readme.md 

### ISSUE THREAD

**Issue by harshit1142** [harshit1142/NewsX#1]
Add relevant content in the readme.md file

**Comment by 29deepanshutyagi** [comment]
hi ,i want to work on this issue ,kindly assign me this issue @harshit1142

**Comment by harshit1142** [comment]
@29deepanshutyagi can you suggest any changes/addition ?

**Comment by 29deepanshutyagi** [comment]
sure, we can add- Eye-catching Title ,with  project description and key features, and with use cases of this project,and contribution guidelines

**Comment by harshit1142** [comment]
@29deepanshutyagi ,Sound good. Do star ⭐ the repo and follow me to start.
