### ISSUE TITLE
Category Based Routing Not Working !

### ISSUE THREAD

**Issue by charliehustlr1792** [harshit1142/NewsX#10]
# It is displaying the same news for all the categories!

## For Sports Category
![Screenshot 2024-10-02 031539](https://github.com/user-attachments/assets/3f32d503-9d08-4a23-aee6-05ead3a3f24d)

## For Entertainement Category
![Screenshot 2024-10-02 031557](https://github.com/user-attachments/assets/a6c6c3da-a923-4478-9d51-09fb29d7081e)

**Hi there! I'd love to work on this issue! Could you please assign it to me? Also, if possible, could we add the following labels: hacktoberfest and gssoc-extd?**

**Comment by ripu2** [comment]
@harshit1142 checkout this PR https://github.com/harshit1142/NewsX/pull/11

**Comment by harshit1142** [comment]
Issue Merged.
