### ISSUE TITLE
Improve website UI

### ISSUE THREAD

**Issue by harshit1142** [harshit1142/NewsX#2]
Free to change Background color, font family,text-color etc

**Comment by charliehustlr1792** [comment]
I can improve the website UI can u pls assign this issue to me

**Comment by harshit1142** [comment]
@charliehustlr1792 Sure, Do star ⭐ the repo and follow me to start.

**Comment by ripu2** [comment]
@harshit1142 , Are we free to use some libraries too ?

**Comment by harshit1142** [comment]
@ripu2 yeah sure, please ensure it don't involve complex building process.
Someone is already assign for the issue

**Comment by ripu2** [comment]
> @ripu2 yeah sure, please ensure it don't involve complex building process. Someone is already assign for the issue

Great

**Comment by ripu2** [comment]
@harshit1142 Is it assigned to someone or can I pick em

**Comment by harshit1142** [comment]
@ripu2 it is already assigned.

**Comment by devashishroychowdhury** [comment]
# I can improve the UI in no time

**Comment by harshit1142** [comment]
@devashishroychowdhury  Assigned. Take your time and come up with a good UI.

Do star ⭐ the repo and follow me to start.

**Comment by VANSH3104** [comment]
@harshit1142 can i work on this as its a week ago to assigned this issue can you assigned it to me

**Comment by harshit1142** [comment]
@VANSH3104 yeah, go ahead.
