### ISSUE TITLE
Data Not Found

### ISSUE THREAD

**Issue by charliehustlr1792** [harshit1142/NewsX#3]
![Screenshot 2024-10-01 200200](https://github.com/user-attachments/assets/23f82eeb-830e-46c3-90bb-b0c9a58f70e5)

**Comment by charliehustlr1792** [comment]
@harshit1142 I can fix this issue can you pls assign this to me also pls add hacktoberfest and gssoc labels

**Comment by harshit1142** [comment]
@charliehustlr1792 Sure

**Comment by ripu2** [comment]
Acknowledged

**Comment by ripu2** [comment]
Please checkout this https://github.com/harshit1142/NewsX/pull/9

**Comment by ripu2** [comment]
> Please checkout this #9

@harshit1142
