### ISSUE TITLE
Optimize Home Component Rendering Using useMemo

### ISSUE THREAD

**Issue by 29deepanshutyagi** [harshit1142/NewsX#4]
The Home component in our React application is currently fetching data from the News API based on category, country, or search input. However, the implementation can lead to unnecessary re-renders and computations, affecting performance.
Proposed Changes:

    Use useMemo for URL Construction:
        Implement useMemo to memoize the API URL based on dependencies (cat, con, searchit). This will prevent the URL from being recomputed on every render, optimizing data fetching.

    Use useCallback for Fetch Function:
        Utilize useCallback to memoize the fetchData function. This ensures that the function only changes when its dependencies change, reducing unnecessary re-renders of the component.

    Improve Loading State Handling:
        Introduce a loading state to give feedback to users while data is being fetched.

    Conditional Rendering of NotFound Component:
        Display the NotFound component only when there are no news articles to show, improving the user experience.

Benefits:

    Improved performance and reduced unnecessary re-renders.
    Enhanced user experience with loading states and better handling of search functionality.

**Comment by 29deepanshutyagi** [comment]
i want to work on this issue @harshit1142 , if you did n't have any issue

**Comment by harshit1142** [comment]
@29deepanshutyagi Assigned. Do star ⭐ the repo and follow me to start
