### ISSUE TITLE
Move API Key to Environment Variables

### ISSUE THREAD

**Issue by 29deepanshutyagi** [harshit1142/NewsX#6]
The current implementation of the Home component in our React application includes a hardcoded API key for the News API

Proposed Solution: To enhance security and protect sensitive information, we should move the API key to environment variables. This can be achieved by:

    Creating a .env file at the root of the project (if it doesn’t already exist).
    Adding the API key to the .env file,

**Comment by harshit1142** [comment]
@29deepanshutyagi Yes, do add.
